
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hp
 */
public class GradeCalculator extends javax.swing.JFrame {

    /**
     * Creates new form GradeCalculator
     */
    public GradeCalculator() {
        initComponents();
         setLocation(400,250);
          setSize(1000,600);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        marks1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        marks2 = new javax.swing.JTextField();
        marks3 = new javax.swing.JTextField();
        marks5 = new javax.swing.JTextField();
        marks4 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablemodel1 = new javax.swing.JTable();
        refresh = new javax.swing.JButton();
        sub4grade = new javax.swing.JTextField();
        sub3grade = new javax.swing.JTextField();
        sub1grade = new javax.swing.JTextField();
        sub2grade = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        sub5grade = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Enter Marks Out Of 100:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 300, 50));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Subject 3:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Subject 4:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Subject 5:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Subject 2:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Subject 1:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 80, 60));
        jPanel1.add(marks1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 200, 40));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("STUDENT GRADE CALCULATOR");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 590, 120));
        jPanel1.add(marks2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 200, 40));
        jPanel1.add(marks3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 200, 40));

        marks5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marks5ActionPerformed(evt);
            }
        });
        jPanel1.add(marks5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 200, 40));

        marks4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marks4ActionPerformed(evt);
            }
        });
        jPanel1.add(marks4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 200, 40));

        tablemodel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255)));
        tablemodel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tablemodel1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Total Marks", "Average %", "GPA", "Grade"
            }
        ));
        jScrollPane1.setViewportView(tablemodel1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 480, 200));

        refresh.setBackground(new java.awt.Color(153, 153, 153));
        refresh.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        refresh.setText("REFRESH");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        jPanel1.add(refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 400, 170, 40));

        sub4grade.setEditable(false);
        jPanel1.add(sub4grade, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, 70, 40));

        sub3grade.setEditable(false);
        jPanel1.add(sub3grade, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 70, 40));

        sub1grade.setEditable(false);
        jPanel1.add(sub1grade, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 70, 40));

        sub2grade.setEditable(false);
        jPanel1.add(sub2grade, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 70, 40));

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("CALCULATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 390, 50));

        sub5grade.setEditable(false);
        jPanel1.add(sub5grade, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 400, 70, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void marks5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marks5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marks5ActionPerformed

    private void marks4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marks4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marks4ActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        // TODO add your handling code here:
        marks1.setText("");
        marks2.setText("");
        marks3.setText("");
        marks4.setText("");
        marks5.setText("");
        sub1grade.setText("");
        sub2grade.setText("");
        sub3grade.setText("");
        sub4grade.setText("");
        sub5grade.setText("");
        DefaultTableModel tb = (DefaultTableModel) tablemodel1.getModel();
        tb.setRowCount(0);
    }//GEN-LAST:event_refreshActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel tb = (DefaultTableModel) tablemodel1.getModel();
        // Calculates marks
        String subject1marks,subject2marks,subject3marks,subject4marks,subject5marks;
        double average;
        double GPA=0;
        double total;
        String grade = null;
        subject1marks = marks1.getText();
        subject2marks = marks2.getText();
        subject3marks = marks3.getText();
        subject4marks = marks4.getText();
        subject5marks = marks5.getText();

        double subject1 = Double.parseDouble(subject1marks);
        double subject2 = Double.parseDouble(subject2marks);
        double subject3 = Double.parseDouble(subject3marks);
        double subject4 = Double.parseDouble(subject4marks);
        double subject5 = Double.parseDouble(subject5marks);
        total = subject1 +subject2+subject3+subject4+subject5;
        average = (total)/5;
        // Subject 1
        if (subject1 >=88 && subject1 <= 100){
            sub1grade.setText("A+");
            GPA = GPA + 4.0;
        }else if (subject1 >= 81 && subject1 <= 87){
            sub1grade.setText("A");
            GPA = GPA + 3.5;
        }else if (subject1 >= 74 && subject1 <= 80){
            sub1grade.setText("B+");
            GPA = GPA + 3.0;
        }else if (subject1 >= 67 && subject1 <= 73){
            sub1grade.setText("B");
            GPA = GPA + 2.5;
        }else if (subject1 >= 60 && subject1 <= 66){
            sub1grade.setText("c+");
            GPA = GPA + 2.0;
        }else if (subject1 >= 50 && subject1 <= 59){
            sub1grade.setText("c");
            GPA = GPA + 1.6;
        }else if (subject1 >= 40 && subject1 <= 49){
            sub1grade.setText("D");
            GPA = GPA + 1.3;
        }else if (subject1 < 40){
            sub1grade.setText("F");
            GPA = GPA + 0.0;
            JOptionPane.showMessageDialog(this,"FAIL");
        }
        // Subject 2
        if (subject2 >=88 && subject2 <= 100){
            sub2grade.setText("A+");
            GPA = GPA + 4.0;
        }else if (subject2 >= 81 && subject2 <= 87){
            sub2grade.setText("A");
            GPA = GPA + 3.5;
        }else if (subject2 >= 74 && subject2 <= 80){
            sub2grade.setText("B+");
            GPA = GPA + 3.0;
        }else if (subject2 >= 67 && subject2 <= 73){
            sub2grade.setText("B");
            GPA = GPA + 2.5;
        }else if (subject2 >= 60 && subject2 <= 66){
            sub2grade.setText("c+");
            GPA = GPA + 2.0;
        }else if (subject2 >= 50 && subject2 <= 59){
            sub2grade.setText("c");
            GPA = GPA + 1.6;
        }else if (subject2 >= 40 && subject2 <= 49){
            sub2grade.setText("D");
            GPA = GPA + 1.3;
        }else if (subject2 < 40){
            sub2grade.setText("F");
            GPA = GPA + 0.0;
            JOptionPane.showMessageDialog(this,"FAIL");
        }
        // Subject 3
        if (subject3 >=88 && subject3 <= 100){
            sub3grade.setText("A+");
            GPA = GPA + 4.0;
        }else if (subject3 >= 81 && subject3 <= 87){
            sub3grade.setText("A");
            GPA = GPA + 3.5;
        }else if (subject3 >= 74 && subject3 <= 80){
            sub3grade.setText("B+");
            GPA = GPA + 3.0;
        }else if (subject3 >= 67 && subject3 <= 73){
            sub3grade.setText("B");
            GPA = GPA + 2.5;
        }else if (subject3 >= 60 && subject3 <= 66){
            sub3grade.setText("c+");
            GPA = GPA + 2.0;
        }else if (subject3 >= 50 && subject3 <= 59){
            sub3grade.setText("c");
            GPA = GPA + 1.6;
        }else if (subject3 >= 40 && subject3 <= 49){
            sub3grade.setText("D");
            GPA = GPA + 1.3;
        }else if (subject3 < 40){
            sub3grade.setText("F");
            GPA = GPA + 0.0;
            JOptionPane.showMessageDialog(this,"FAIL");
        }
        // Subject 4
        if (subject4 >=88 && subject4 <= 100){
            sub4grade.setText("A+");
            GPA = GPA + 4.0;
        }else if (subject4 >= 81 && subject4 <= 87){
            sub4grade.setText("A");
            GPA = GPA + 3.5;
        }else if (subject4 >= 74 && subject4 <= 80){
            sub4grade.setText("B+");
            GPA = GPA + 3.0;
        }else if (subject4 >= 67 && subject4 <= 73){
            sub4grade.setText("B");
            GPA = GPA + 2.5;
        }else if (subject4 >= 60 && subject4 <= 66){
            sub4grade.setText("c+");
            GPA = GPA + 2.0;
        }else if (subject4 >= 50 && subject4 <= 59){
            sub4grade.setText("c");
            GPA = GPA + 1.6;
        }else if (subject4 >= 40 && subject4 <= 49){
            sub4grade.setText("D");
            GPA = GPA + 1.3;
        }else if (subject4 < 40){
            sub4grade.setText("F");
            GPA = GPA + 0.0;
            JOptionPane.showMessageDialog(this,"FAIL");
        }
        // Subject 5
        if (subject5 >=88 && subject5 <= 100){
            sub5grade.setText("A+");
            GPA = GPA + 4.0;
        }else if (subject5 >= 81 && subject5 <= 87){
            sub5grade.setText("A");
            GPA = GPA + 3.5;
        }else if (subject5 >= 74 && subject5 <= 80){
            sub5grade.setText("B+");
            GPA = GPA + 3.0;
        }else if (subject5 >= 67 && subject5 <= 73){
            sub5grade.setText("B");
            GPA = GPA + 2.5;
        }else if (subject5 >= 60 && subject5 <= 66){
            sub5grade.setText("c+");
            GPA = GPA + 2.0;
        }else if (subject5 >= 50 && subject5 <= 59){
            sub5grade.setText("c");
            GPA = GPA + 1.6;
        }else if (subject5 >= 40 && subject5 <= 49){
            sub5grade.setText("D");
            GPA = GPA + 1.3;
        }else if (subject5 < 40){
            sub5grade.setText("F");
            GPA = GPA + 0.00;
            JOptionPane.showMessageDialog(this,"FAIL");
        }

        GPA = GPA / 5;
        if (GPA >= 3.5 && GPA <=4.0){
            grade = "A+";
        }else if (GPA >= 3.0 && GPA <= 3.5){
            grade = "A";
        } else if (GPA >= 2.5 && GPA <=3.0){
            grade = "B+";
        } else if ((GPA >= 2.0 && GPA <=2.5)){
            grade = "B";
        } else if (GPA >= 1.6 && GPA <=2.0){
            grade = "C+";
        } else if (GPA >= 1.3 && GPA <=1.6){
            grade = "C";
        } else if (GPA >= 1.0 && GPA <=1.3){
            grade = "D";
        } else if (GPA == 0.00){
            grade = "F";
        }

        Object[] row ={
            total , average , GPA ,grade
        };
        tb.addRow(row);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GradeCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GradeCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GradeCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GradeCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GradeCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField marks1;
    private javax.swing.JTextField marks2;
    private javax.swing.JTextField marks3;
    private javax.swing.JTextField marks4;
    private javax.swing.JTextField marks5;
    private javax.swing.JButton refresh;
    private javax.swing.JTextField sub1grade;
    private javax.swing.JTextField sub2grade;
    private javax.swing.JTextField sub3grade;
    private javax.swing.JTextField sub4grade;
    private javax.swing.JTextField sub5grade;
    private javax.swing.JTable tablemodel1;
    // End of variables declaration//GEN-END:variables
}
